version: '2.2'
services:
  R1:
    image: 'my_node:2.0'
    privileged: true
    tty: true
    networks:
      my_netA:
        ipv4_address: 10.0.14.4
      my_netB:
        ipv4_address: 10.0.11.4
  R2:
    image: 'my_node:2.0'
    privileged: true
    tty: true
    networks:
      my_netB:
        ipv4_address: 10.0.11.3
      my_netC:
        ipv4_address: 10.0.12.3
  R3:
    image: 'my_node:2.0'
    privileged: true
    tty: true
    networks:
      my_netC:
        ipv4_address: 10.0.12.4
      my_netD:
        ipv4_address: 10.0.15.4
  hostA:
    image: 'my_node:1.0'
    privileged: true
    tty: true
    networks:
      my_netA:
        ipv4_address: 10.0.14.3
  hostB:
    image: 'my_node:1.0'
    privileged: true
    tty: true
    networks:
      my_netD:
        ipv4_address: 10.0.15.3
networks:
  my_netA:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.14.0/24
          gateway: 10.0.14.1
  my_netB:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.11.0/24
          gateway: 10.0.11.1
  my_netC:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.12.0/24
          gateway: 10.0.12.1
  my_netD:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.15.0/24
          gateway: 10.0.15.1

